@Clinic_Api_Host = https://localhost:8585

### Get Sections
GET {{Clinic_Api_Host}}/api/main/getSections
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU1NTM0MjE2LCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.m2aC3StvAxkQ8MWLhJDmDW0vkMv3i6rK0qxQXJH6k5A

### Get Clinics
GET {{Clinic_Api_Host}}/api/main/getClinics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJuaW1hIiwicm9sZSI6IkFkbWluIiwiZXhwIjoxNzU2ODA1NjE4LCJpc3MiOiJDbGluaWMuQXBpIiwiYXVkIjoiQ2xpbmljLkFwaS5Vc2VycyJ9.S8z4iLf7sKv6IOaJNX2CVFGjM3IZaG5yK84Sv-VYTd8
Content-Type: application/json

### Save Job
POST {{Clinic_Api_Host}}/api/main/saveJob
Authorization: Bearer 
Content-Type: application/json
{
  "name": "nima",
  "editOrNew": -1
}

### Get Jobs
GET {{Clinic_Api_Host}}/api/main/getJobs
Authorization: Bearer
Content-Type: application/json

### Delete Job 
GET {{Clinic_Api_Host}}/api/main/deleteJob/1
Authorization: Bearer
Content-Type: application/json

### Get Countries
GET {{Clinic_Api_Host}}/api/contact/getCountries
Authorization: Bearer
Content-Type: application/json

### Save Product
POST {{Clinic_Api_Host}}/api/main/saveProduct
Authorization: Bearer
Content-Type: application/json
{
  "code": null,
  "name": null,
  "serialNumber": null,
  "supplier": null,
  "price": 100,
  "stockLevel": null,
  "notes": null,
  "isActive": true,
  "editOrNew": -1
}

### Get Products
GET {{Clinic_Api_Host}}/api/main/getProducts
Authorization: Bearer
Content-Type: application/json

### Delete Product
GET {{Clinic_Api_Host}}/api/main/deleteProduct/1
Authorization: Bearer
Content-Type: application/json

### Save Note
POST {{Clinic_Api_Host}}/api/main/saveNote
Authorization: Bearer
Content-Type: application/json
{
  "message": "salam",
  "patientId": 1,
  "editOrNew": -1,
  "orderOf": null
}

### Get Notes 
GET {{Clinic_Api_Host}}/api/main/getNotes/1
Authorization: Bearer
Content-Type: application/json

### Delete Note 
GET {{Clinic_Api_Host}}/api/main/deleteNote/1
Authorization: Bearer
Content-Type: application/json

### Save Doctor Schedule
POST {{Clinic_Api_Host}}/api/main/saveDoctorSchedule
Authorization: Bearer
Content-Type: application/json
{
  "businessId": 2,
  "practitionerId": 3,
  "day": 2,
  "fromTime": 00:00:0000T,
  "toTime": 00:00:0000T,
  "isBreak": true,
  "isActive": true,
  "duration": null,
  "editOrNew": -1
}

### Get Doctor Schedules
GET {{Clinic_Api_Host}}/api/main/getDoctorSchedules
Authorization: Bearer
Content-Type: application/json

### Delete Doctor Schedule
GET {{Clinic_Api_Host}}/api/main/deleteDoctorSchedule/2
Authorization: Bearer
Content-Type: application/json

### Save User Appointment Setting 
POST {{Clinic_Api_Host}}/api/main/saveUserAppointmentsSettings
Authorization: Bearer
Content-Type: application/json
{
  "practitionerId": 2,
  "businessId": 2,
  "defaultAppointmentTypeId": null,
  "newPatientAppointmentTypeId": null,
  "outOfTurn": 5,
  "timeSlotSize": 6,
  "calendarTimeFrom": 10,
  "calendarTimeTo": 15,
  "multipleAppointment": true,
  "editOrNew": -1
}

### Get User Appointment Settings
POST {{Clinic_Api_Host}}/api/main/getUserAppointmentsSettings
Authorization: Bearer
Content-Type: application/json
{
  "userId": null,
  "businessId": null
}

### Save Business
POST {{Clinic_Api_Host}}/api/main/saveBusiness
Authorization: Bearer
Content-Type: application/json
{
  "name": null,
  "address": null,
  "address2": null,
  "city": null,
  "state": null,
  "postCode": null,
  "countryId": null,
  "contactInformation": null,
  "displayInOnlineBooking": true,
  "location": null,
  "zoom": null,
  "infoEmail": null,
  "isServiceBase": true,
  "showInvoiceInRecord": true,
  "checkScheduleOnInvoice": true,
  "isInPatient": true,
  "SMSEnabled": true,
  "appointmentByOutOfRange": null,
  "serviceId": 2,
  "editOrNew": -1
}

### Get Businesses
GET {{Clinic_Api_Host}}/api/main/getBusinesses
Authorization: Bearer
Content-Type: application/json

### Delete Business
GET {{Clinic_Api_Host}}/api/main/deleteBusiness/1
Authorization: Bearer
Content-Type: application/json

### Get Time Exceptions
GET {{Clinic_Api_Host}}/api/main/getTimeExceptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjU5NTk5ODIsImlhdCI6MTc2NTM1NTE4MiwidXNlcklkIjoiMiIsInVzZXJuYW1lIjoibmltYSIsInVzZXJSb2xlIjoiQWRtaW4iLCJuYmYiOjE3NjUzNTUxODJ9.Hv2MIk7K-iKo6r92yDS-xSSM33WKEedAo7SfrN1klbg
Content-Type: application/json